name: Generate pnpm lockfile patch

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Regenerate lockfile
        run: pnpm install --lockfile-only --ignore-scripts

      - name: Save lockfile patch
        run: git diff --binary -- pnpm-lock.yaml > pnpm-lockfile-update.patch

      - name: Upload lockfile patch
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pnpm-lockfile-update-${{ github.sha }}-${{ github.run_attempt }}
          path: pnpm-lockfile-update.patch
          if-no-files-found: error
